apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-client
  namespace: token-test

---
apiVersion: v1
kind: Pod
metadata:
  name: token-client
  namespace: token-test
spec:
  containers:
  - image: kangwoo/token-client
    name: token-client
    ports:
    - containerPort: 8090
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: token-client
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
